export const SUBSCRIPTION_PLANS = [
  {
    name: 'Free',
    slug: 'free',
    description: 'Access free courses and track learning progress.',
    price: '0.00',
    billingPeriod: 'monthly',
    aiCredits: 0,
    trialDays: 0,
    stripePriceId: null,
    entitlements: [],
  },
  {
    name: 'Premium Monthly',
    slug: 'premium-monthly',
    description: 'Premium courses, Apsara AI, and certificates.',
    price: '9.99',
    billingPeriod: 'monthly',
    aiCredits: 200,
    trialDays: 7,
    stripePriceId: process.env.STRIPE_MONTHLY_PRICE_ID || null,
    entitlements: ['courses:premium', 'ai:tutor', 'certificates'],
  },
  {
    name: 'Premium Yearly',
    slug: 'premium-yearly',
    description: 'A full year of premium learning at the best value.',
    price: '99.00',
    billingPeriod: 'yearly',
    aiCredits: 3000,
    trialDays: 7,
    stripePriceId: process.env.STRIPE_YEARLY_PRICE_ID || null,
    entitlements: ['courses:premium', 'ai:tutor', 'certificates'],
  },
];
